version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: newoteg_postgres
    restart: always
    environment:
      POSTGRES_USER: newoteg_user
      POSTGRES_PASSWORD: newoteg_password
      POSTGRES_DB: newoteg_db
    ports:
      - '5432:5432'
    volumes:
      - newoteg_postgres_data:/var/lib/postgresql/data

volumes:
  newoteg_postgres_data:
    driver: local
