-- Reconstructed migration: aligns the local migration history with the
-- production schema already recorded in _prisma_migrations.

ALTER TABLE "client" ALTER COLUMN "otp_code" TYPE TEXT;

ALTER TABLE "notification" ADD COLUMN "actor_id" TEXT;
ALTER TABLE "notification" ADD COLUMN "actor_name" VARCHAR(100);
ALTER TABLE "notification" ADD COLUMN "actor_role" VARCHAR(20);

ALTER TYPE "TypeNotification" ADD VALUE IF NOT EXISTS 'PRODUIT_SUPPRIME';
ALTER TYPE "TypeNotification" ADD VALUE IF NOT EXISTS 'CATEGORIE_SUPPRIMEE';
ALTER TYPE "TypeNotification" ADD VALUE IF NOT EXISTS 'VENTE_MAJ';
ALTER TYPE "TypeNotification" ADD VALUE IF NOT EXISTS 'ACHAT_MAJ';
ALTER TYPE "TypeNotification" ADD VALUE IF NOT EXISTS 'ACHAT_SUPPRIME';
ALTER TYPE "TypeNotification" ADD VALUE IF NOT EXISTS 'COMPTE_CREE';
ALTER TYPE "TypeNotification" ADD VALUE IF NOT EXISTS 'COMPTE_MAJ';
ALTER TYPE "TypeNotification" ADD VALUE IF NOT EXISTS 'COMPTE_SUPPRIME';
ALTER TYPE "TypeNotification" ADD VALUE IF NOT EXISTS 'FOURNISSEUR_CREE';
ALTER TYPE "TypeNotification" ADD VALUE IF NOT EXISTS 'FOURNISSEUR_MAJ';
ALTER TYPE "TypeNotification" ADD VALUE IF NOT EXISTS 'FOURNISSEUR_SUPPRIME';
ALTER TYPE "TypeNotification" ADD VALUE IF NOT EXISTS 'CAISSE_CREEE';
ALTER TYPE "TypeNotification" ADD VALUE IF NOT EXISTS 'CAISSE_MAJ';
ALTER TYPE "TypeNotification" ADD VALUE IF NOT EXISTS 'CAISSE_SUPPRIMEE';
ALTER TYPE "TypeNotification" ADD VALUE IF NOT EXISTS 'MOUVEMENT_STOCK_CREE';
